language: java
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
install:
  - mvn package
script:
  - mvn clean
  - mvn cobertura:cobertura
  - mvn qulice:check
after_success:
  - bash <(curl -s https://codecov.io/bash)
