language: java
jdk: oraclejdk8
cache:
  directories:
  - $HOME/.m2
sudo: required
services:
  - docker
install:
  - mvn package
script:
  - mvn clean
  - mvn verify -P integration-test
  - mvn cobertura:cobertura
after_success:
  - bash <(curl -s https://codecov.io/bash)
